DROP TABLE IF EXISTS bill;
CREATE TABLE bill(
    ID VARCHAR(64) NOT NULL   COMMENT 'ID' ,
    HAPPEN_DATE DATETIME NOT NULL   COMMENT '发生时间' ,
    REMARK VARCHAR(255) NOT NULL   COMMENT '备注' ,
    CATEGORY VARCHAR(6) NOT NULL   COMMENT '账单分类' ,
    PAY_CHANNEL VARCHAR(6) NOT NULL   COMMENT '支付渠道' ,
    AMOUNT DECIMAL(24,6) NOT NULL   COMMENT '金额' ,
    CREATE_TIME DATETIME    COMMENT '创建时间' ,
    UPDATE_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '账单';

DROP TABLE IF EXISTS file_import_history;
CREATE TABLE file_import_history(
    ID VARCHAR(64) NOT NULL   COMMENT 'ID' ,
    FILE_NAME VARCHAR(255) NOT NULL   COMMENT '文件名' ,
    FILE_ROW INT NOT NULL   COMMENT '文件行数' ,
    FILE_MD5 VARCHAR(32) NOT NULL   COMMENT '文件的MD5值' ,
    CREATE_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATE_TIME DATETIME NOT NULL   COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '文件导入记录';
