jasypt:
  encrytor:
    #用来加解密的salt值
    password: Abc2er!@#$
    #用来使用新的算法，默认为org.jasypt.salt.NoOPIVGenerator,这样的话我们就无法使用命令行中生成的密文
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator
spring:
  application:
    name: transaction-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: '******'
    druid:
      filters:
        stat,wall
  aop:
    proxy-target-class: false
server:
  port: 8080
logging:
  level:
    cn.yangwanhao:
      debug
    org.mybatis:
      debug
token:
  signature: 1234567890
